### ISSUE TITLE
Add sublayouts option

### ISSUE THREAD

**Issue by ivangretsky** [wireframe-framework/wireframe#23]
Good day!

There was a [conversation about sublayouts](https://processwire.com/talk/topic/26489-sublayouts-or-a-way-to-imitate-template-inheritance/) in the forums. 

@teppokoivula said that he
> just mocked up locally a setup where layouts can be embedded within layouts

Creating this issue, so this idea doen't get lost. And as I need it))

**Comment by teppokoivula** [comment]
At least for now I'll close this issue — as discussed at the support forum, I believe it makes more sense to use Partials here, rather than add a new concept of sublayouts (or the $layouts API variable, which I originally considered).

Let me know if you disagree, though, and we can reopen this :)

**Comment by ivangretsky** [comment]
Thanks for your work on this!
I will play around with new partials' features and write back if something doesn't work out.
