### ISSUE TITLE
Error calling Wireframe::partial with a path to file without .php

### ISSUE THREAD

**Issue by ivangretsky** [wireframe-framework/wireframe#24]
Good day!

I am getting an error when calling `Wireframe::partia`l with a path to file without `.php`.

So this:
```php
Wireframe::partial('test');
Wireframe::partial('test', []);
```

results with this error: `Exception: Partial file not found: /XYZ/site/templates/wireframe/partials/testphp (in [/XYZ/site/modules/Wireframe/lib/Partial.php]`

When giving the whole path (like below), there is no error:
```php
Wireframe::partial('test.php');
```

The [docs](https://wireframe-framework.com/docs/static-utility-methods/) say not using the extension should be possible.

**Comment by teppokoivula** [comment]
Thanks, @ivangretsky — should be fixed now :)
