### ISSUE TITLE
PHP 8.2+ compatability 

### ISSUE THREAD

**Issue by ivangretsky** [wireframe-framework/wireframe#27]
Good day!

Seems like php 8.2 is becoming a must for some PW modules. Maybe it is time to try to deal with Wireframe-caused deprecations?

![image](https://github.com/wireframe-framework/Wireframe/assets/6697626/251575f0-e5e2-433d-ac82-522515c1134e)

**Comment by teppokoivula** [comment]
Hey @ivangretsky

and sorry for the delay! The issues visible in your screenshot should be fixed now in 0.29.2. Let me know if you continue to experience similar issues.

I'm not running PHP 8.2 here quite yet :)
