### ISSUE TITLE
WireRender Pattern Alternative

### ISSUE THREAD

**Issue by clsource** [wireframe-framework/wireframe#8]
Hello @teppokoivula 
I think this is a wonderful addition to the ProcessWire ecosystem.

Please it would be awesome if you could add  https://github.com/joyofpw/wire-render-pattern to the
https://wireframe-framework.com/about/alternatives/ list.

Thanks 👍

**Comment by teppokoivula** [comment]
Hey @clsource, thanks for pointing this out. I've added a note about Wire Render Pattern.
