### ISSUE TITLE
TypeError: Return value of Config::getPaths()

### ISSUE THREAD

**Issue by craigrodway** [wireframe-framework/wireframe#9]
Hello! 👋 

With 0.13.0, I'm getting the following error when going to the module settings page:

> Uncaught TypeError: Return value of Wireframe\Config::getPaths() must be of the type array, object returned in [path]\site\modules\Wireframe\lib\Config.php:181

It is fixed by changing the definition line from/to:

```protected function getPaths(): array {```

```protected function getPaths(): object {```

In that function, `$paths` is treated as an object, and is retrieved from `$this->wireframe->paths`, which is set to an object using `setPaths()`:

```$this->paths = (object) $paths```

Not sure if it should be an array or an object - but thought I'd let you know! :)

**Comment by teppokoivula** [comment]
Thanks @craigrodway! Return type was indeed supposed to be object, not array :)

**Comment by craigrodway** [comment]
No problem, and thanks again for Wireframe! 🙌
